export const careProfiles: Record<string, {
  category: string;
  water_level: string;
  sunlight: string;
  difficulty: string;
  environment_recommendation: string;
  care_note: string;
}> = {
  고무나무: {
    category: "관엽",
    water_level: "보통",
    sunlight: "밝은 간접광",
    difficulty: "쉬움",
    environment_recommendation: "밝은 간접광, 찬바람 없는 실내, 흙 윗부분이 마른 뒤 급수",
    care_note: "과습과 급격한 환경 변화에 주의",
  },
  고무나무미니1: {
    category: "관엽",
    water_level: "보통",
    sunlight: "밝은 간접광",
    difficulty: "쉬움",
    environment_recommendation: "밝은 간접광, 통풍 좋은 실내",
    care_note: "작은 화분이면 마름 속도를 자주 확인",
  },
  라임오랜지미니: {
    category: "과수",
    water_level: "보통~자주",
    sunlight: "강한 햇빛 선호",
    difficulty: "어려움",
    environment_recommendation: "가능한 긴 직사광, 따뜻한 온도, 성장기 균일한 수분",
    care_note: "꽃/새순 시기 건조 스트레스 주의",
  },
  라임오렌지나무: {
    category: "과수",
    water_level: "보통~자주",
    sunlight: "강한 햇빛 선호",
    difficulty: "보통",
    environment_recommendation: "직사광 많은 창가나 베란다, 배수 좋은 흙",
    care_note: "새순 시기 건조 주의",
  },
  레몬타임: {
    category: "허브",
    water_level: "보통~자주",
    sunlight: "강한 햇빛 선호",
    difficulty: "쉬움",
    environment_recommendation: "강한 빛, 배수 좋은 흙, 통풍",
    care_note: "과습 피하고 마름 확인 후 급수",
  },
  로즈마리: {
    category: "허브",
    water_level: "적게~보통",
    sunlight: "강한 햇빛 선호",
    difficulty: "보통",
    environment_recommendation: "강한 직사광, 건조한 공기, 배수 좋은 흙",
    care_note: "젖은 흙이 오래 유지되면 뿌리 문제 위험",
  },
  루꼴라: {
    category: "채소",
    water_level: "자주",
    sunlight: "밝은 빛~햇빛",
    difficulty: "쉬움",
    environment_recommendation: "밝은 빛, 선선한 온도, 균일한 수분",
    care_note: "마르면 상태가 빠르게 나빠짐",
  },
  바질: {
    category: "허브",
    water_level: "자주",
    sunlight: "강한 햇빛 선호",
    difficulty: "쉬움",
    environment_recommendation: "따뜻한 환경, 충분한 빛, 촉촉하지만 질척이지 않은 흙",
    care_note: "저온과 건조에 민감",
  },
  블루베리: {
    category: "과수",
    water_level: "자주",
    sunlight: "햇빛 선호",
    difficulty: "어려움",
    environment_recommendation: "충분한 햇빛, 산성 배지, 건조하지 않게 균일한 수분",
    care_note: "건조와 물 고임 모두 주의",
  },
  샐러리: {
    category: "채소",
    water_level: "자주",
    sunlight: "밝은 빛",
    difficulty: "보통",
    environment_recommendation: "밝은 빛, 선선하고 촉촉한 환경",
    care_note: "수분 부족 시 잎 처짐",
  },
  아틀란티스: {
    category: "세덤/다육",
    water_level: "적게",
    sunlight: "밝은 빛 선호",
    difficulty: "쉬움",
    environment_recommendation: "밝은 빛, 강한 통풍, 완전 배수",
    care_note: "다육류라 과습이 가장 큰 위험",
  },
  오렌지자스민: {
    category: "목본",
    water_level: "보통",
    sunlight: "햇빛 선호",
    difficulty: "보통",
    environment_recommendation: "밝은 빛~햇빛, 따뜻한 온도, 성장기 수분 체크",
    care_note: "성장기엔 물 마름이 빨라질 수 있음",
  },
  올리브: {
    category: "목본/과수",
    water_level: "적게~보통",
    sunlight: "강한 햇빛 선호",
    difficulty: "보통",
    environment_recommendation: "직사광 6시간 이상, 건조한 공기, 배수 좋은 흙",
    care_note: "흙이 오래 젖지 않게 관리",
  },
  유칼립투스: {
    category: "목본",
    water_level: "보통",
    sunlight: "강한 햇빛 선호",
    difficulty: "어려움",
    environment_recommendation: "강한 빛, 통풍, 급격한 건조/과습 방지",
    care_note: "마름과 과습 모두 민감",
  },
  케일: {
    category: "채소",
    water_level: "보통~자주",
    sunlight: "햇빛 선호",
    difficulty: "쉬움",
    environment_recommendation: "햇빛 또는 반양지, 꾸준한 토양수분",
    care_note: "성장기 수분 필요",
  },
  파슬리: {
    category: "채소/허브",
    water_level: "자주",
    sunlight: "밝은 빛~햇빛",
    difficulty: "쉬움",
    environment_recommendation: "밝은 빛, 흙 윗부분이 마르기 전후로 급수",
    care_note: "작은 화분은 마름 체크 필요",
  },
  "파슬리(미니)": {
    category: "채소/허브",
    water_level: "자주",
    sunlight: "밝은 빛~햇빛",
    difficulty: "쉬움",
    environment_recommendation: "밝은 빛, 작은 화분 수분 모니터링",
    care_note: "작은 화분이면 더 자주 체크",
  },
  흰싸리: {
    category: "관목",
    water_level: "보통",
    sunlight: "햇빛 좋아함",
    difficulty: "보통",
    environment_recommendation: "햇빛 좋은 자리, 계절별 마름 속도 관찰",
    care_note: "계절 영향이 큰 편",
  },
};
